version:
  '3.8'

services:
  api:
    build: ./api
    image: milk8248/asuswrt-floorplan-api:0.0.1
    container_name: asuswrt-floorplan-api
    volumes:
      - ./api:/usr/src/app

  nginx:
    build: .
    image: milk8248/asuswrt-floorplan-nginx:0.0.1
    container_name: asuswrt-floorplan-nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
#
#  web:
#    build: ./web
#    image: milk8248/asuswrt-floorplan-web:0.0.1
#    container_name: asuswrt-floorplan-web
#    volumes:
#      - web-dist:/app/dist