version:
  '3.8'

services:
  api:
    build: ./api
    image: milk8248/asuswrt-floorplan-api:0.0.1
    container_name: asuswrt-floorplan-api
    volumes:
      - ./api:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: asuswrt-floorplan-nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/etc/nginx/html
    depends_on:
      - api

volumes:
  mongo-data:
    driver: local